
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgbqcrwzacyjvettxqbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnYnFjcnd6YWN5anZldHR4cWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTU5NTYsImV4cCI6MjA1ODEzMTk1Nn0.D9KFUHz3hYLLBRZLjwbp1m_qWMYUyu3pATjXCKijgOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
